version: "3.9"

services:
  postgres:
    image: postgres:16.2-alpine
    restart: always

    volumes:
        - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=${USER}
        - POSTGRES_PASSWORD=${PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    
        